# Generated by Django 4.2.6 on 2023-10-31 09:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_staffuser_date_joined_staffuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='staffuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
