# Generated by Django 4.2.6 on 2023-10-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_staffuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
    ]
