# Generated by Django 4.2.6 on 2023-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_staffuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='work_schedule',
            field=models.DateField(blank=True, null=True, verbose_name='График работы'),
        ),
    ]
