# Generated by Django 4.2.6 on 2023-11-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_staffuser_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='is_admin_user',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
