# Generated by Django 4.2.6 on 2023-11-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_staffuser_is_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('image', models.ImageField(upload_to='media/staff_images', verbose_name='Фото')),
                ('birth_date', models.DateField(default='2000-09-12', verbose_name='Дата рождения')),
                ('residential_address', models.CharField(max_length=255, verbose_name='Адрес проживвание')),
                ('home_number', models.CharField(max_length=150, verbose_name='Номер дома')),
                ('password_image', models.ImageField(upload_to='media/staff_password_image', verbose_name='Фото паспорта')),
                ('work_schedule', models.DateField(blank=True, null=True, verbose_name='График работы')),
                ('is_admin_user', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Профиль Сотрудника',
                'verbose_name_plural': 'Профиль Сотрудников',
            },
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='is_admin_user',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='password_image',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='work_schedule',
        ),
    ]
