# Generated by Django 4.2.6 on 2023-11-05 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staffusersprofile_remove_staffuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffusersprofile',
            name='work_schedule',
        ),
        migrations.AddField(
            model_name='staffusersprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day_shift', 'Дневная смена'), ('night_shift', 'Вечерняя смена'), ('day_off', 'Выходной')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddField(
            model_name='staffusersprofile',
            name='work_schedules',
            field=models.ManyToManyField(related_name='profiles', to='users.workschedule', verbose_name='График работы'),
        ),
        migrations.CreateModel(
            name='MonthlyWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('schedule', models.ManyToManyField(to='users.workschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_work_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
