# Generated by Django 4.2.6 on 2023-11-05 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_staffusersprofile_work_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyworkschedule',
            options={'verbose_name': 'График работы на месяц'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'График работы сотрудника'},
        ),
        migrations.AlterField(
            model_name='monthlyworkschedule',
            name='schedule',
            field=models.ManyToManyField(to='users.workschedule', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='monthlyworkschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_work_schedule', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='date',
            field=models.DateField(verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='shift_type',
            field=models.CharField(choices=[('day_shift', 'Дневная смена с 10:00 до 17:00'), ('night_shift', 'Вечерняя смена с 17:00 до 23:00'), ('day_off', 'Выходной')], max_length=20, verbose_name='Выберите смену'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник'),
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_position', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Должность сотрудника',
            },
        ),
        migrations.AddField(
            model_name='monthlyworkschedule',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staffposition', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staffposition', verbose_name='Должность'),
        ),
    ]
