# Generated by Django 4.2.6 on 2023-11-09 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_monthlyworkschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyworkschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_work_schedule', to='users.staffuser', verbose_name='сотрудник'),
        ),
        migrations.AlterField(
            model_name='staffposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_position', to='users.staffuser', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='staffusersprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.staffuser'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='users.staffuser', verbose_name='сотрудник'),
        ),
    ]
