# Generated by Django 4.2.6 on 2023-12-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0003_alter_branches_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Лимит')),
                ('arrival_date', models.DateField(verbose_name='Дата прихода')),
                ('category', models.CharField(choices=[('ready_products', 'Готовые продукты'), ('raw_materials', 'Сырье'), ('running_out_products', 'Заканчивающиеся продукты')], max_length=20, verbose_name='Категория')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branches', verbose_name='Филиал')),
            ],
            options={
                'verbose_name_plural': 'Склад',
                'ordering': ['-arrival_date', 'name'],
            },
        ),
    ]
