# Generated by Django 4.2.6 on 2023-12-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branches",
            name="date",
            field=models.DateTimeField(
                null=True, verbose_name="График работы: Выберите дату"
            ),
        ),
        migrations.AlterField(
            model_name="branches",
            name="work_schedule",
            field=models.CharField(
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                default="work_day",
                max_length=20,
                null=True,
            ),
        ),
    ]
