# Generated by Django 4.2.6 on 2023-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
        ("branches", "0002_remove_coffeeshop_category_remove_coffeeshop_menu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshop",
            name="category",
            field=models.ManyToManyField(
                related_name="coffee_shop", to="menu.category", verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="coffeeshop",
            name="menu",
            field=models.ManyToManyField(
                related_name="menu", to="menu.menu", verbose_name="Меню"
            ),
        ),
    ]
