# Generated by Django 4.2.6 on 2023-12-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0002_branches_date_alter_branches_work_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branches",
            name="date",
            field=models.DateField(
                null=True, verbose_name="График работы: Выберите дату"
            ),
        ),
    ]
