# Generated by Django 4.2.6 on 2023-12-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0003_alter_branches_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branches",
            name="work_schedule",
        ),
        migrations.AddField(
            model_name="branches",
            name="friday",
            field=models.CharField(
                blank=True,
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="branches",
            name="monday",
            field=models.CharField(
                blank=True,
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="branches",
            name="saturday",
            field=models.CharField(
                blank=True,
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="branches",
            name="sunday",
            field=models.CharField(
                blank=True,
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="branches",
            name="thursday",
            field=models.CharField(
                blank=True,
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="branches",
            name="tuesday",
            field=models.CharField(
                blank=True,
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="branches",
            name="wednesday",
            field=models.CharField(
                blank=True,
                choices=[("work_day", "С 08:00 до 00:00"), ("day_off", "Выходной")],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
    ]
