# Generated by Django 4.2.6 on 2023-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0006_branches_work_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branches",
            name="work_schedule",
        ),
        migrations.AlterField(
            model_name="branches",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название филиала"),
        ),
    ]
