# Generated by Django 4.2.6 on 2023-12-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0007_remove_branches_work_schedule_alter_branches_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branches",
            name="date",
        ),
        migrations.AddField(
            model_name="branches",
            name="friday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="friday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="monday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="monday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="saturday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="saturday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="sunday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="sunday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="thursday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="thursday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="tuesday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="tuesday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="wednesday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branches",
            name="wednesday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="branches",
            name="friday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branches",
            name="monday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branches",
            name="saturday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branches",
            name="sunday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branches",
            name="thursday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branches",
            name="tuesday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branches",
            name="wednesday",
            field=models.BooleanField(default=False),
        ),
    ]
