# Generated by Django 4.2.6 on 2024-01-01 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0008_remove_branches_date_branches_friday_end_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branches",
            options={"verbose_name": "Филиал", "verbose_name_plural": "Филиалы"},
        ),
    ]
