# Generated by Django 4.2.6 on 2023-11-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="password",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
