# Generated by Django 4.2.6 on 2023-12-14 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_remove_menu_ingredients"),
        ("administrator", "0004_alter_menuingredient_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuIngredient",
        ),
    ]
