# Generated by Django 4.2.6 on 2023-12-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_inventoryitem_is_running_out_and_more'),
        ('menu', '0014_alter_category_slug'),
        ('administrator', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_ingredients', to='menu.menu'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together={('menu_item', 'product')},
        ),
    ]
