# Generated by Django 4.2.6 on 2023-11-28 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("order", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="orders",
            field=models.ManyToManyField(
                related_name="customer_orders", to="order.orderitem"
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="staffuserprofile",
            index=models.Index(fields=["role"], name="customers_s_role_id_251c28_idx"),
        ),
        migrations.AddIndex(
            model_name="staffuserprofile",
            index=models.Index(
                fields=["full_name"], name="customers_s_full_na_9f6204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffuserprofile",
            index=models.Index(
                fields=["-created_at"], name="customers_s_created_35a853_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["full_name"], name="customers_c_full_na_e08602_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["-created_at"], name="customers_c_created_484201_idx"
            ),
        ),
    ]
