# Generated by Django 4.2.6 on 2023-11-28 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="username",
        ),
    ]
