# Generated by Django 4.2.6 on 2023-12-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_baseuser_managers_baseuser_is_verify_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="baseuser",
            name="username",
        ),
        migrations.AddField(
            model_name="baseuser",
            name="login",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
