# Generated by Django 4.2.6 on 2023-12-11 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_remove_baseuser_date_joined_remove_baseuser_email_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseuser",
            old_name="full_name",
            new_name="username",
        ),
    ]
