# Generated by Django 4.2.6 on 2023-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_remove_baseuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
