# Generated by Django 4.2.6 on 2023-11-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_baseuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="is_verify",
            field=models.BooleanField(default=False),
        ),
    ]
