# Generated by Django 4.2.6 on 2023-12-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_baseuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="work_schedule",
        ),
        migrations.AddField(
            model_name="baseuser",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="График работы"),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="friday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_shift", "Дневная смена с 10:00 до 17:00"),
                    ("night_shift", "Вечерняя смена с 17:00 до 23:00"),
                    ("day_off", "Выходной"),
                ],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="monday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_shift", "Дневная смена с 10:00 до 17:00"),
                    ("night_shift", "Вечерняя смена с 17:00 до 23:00"),
                    ("day_off", "Выходной"),
                ],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="saturday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_shift", "Дневная смена с 10:00 до 17:00"),
                    ("night_shift", "Вечерняя смена с 17:00 до 23:00"),
                    ("day_off", "Выходной"),
                ],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="sunday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_shift", "Дневная смена с 10:00 до 17:00"),
                    ("night_shift", "Вечерняя смена с 17:00 до 23:00"),
                    ("day_off", "Выходной"),
                ],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="thursday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_shift", "Дневная смена с 10:00 до 17:00"),
                    ("night_shift", "Вечерняя смена с 17:00 до 23:00"),
                    ("day_off", "Выходной"),
                ],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="tuesday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_shift", "Дневная смена с 10:00 до 17:00"),
                    ("night_shift", "Вечерняя смена с 17:00 до 23:00"),
                    ("day_off", "Выходной"),
                ],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="wednesday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day_shift", "Дневная смена с 10:00 до 17:00"),
                    ("night_shift", "Вечерняя смена с 17:00 до 23:00"),
                    ("day_off", "Выходной"),
                ],
                max_length=20,
                null=True,
                verbose_name="Выберите смену",
            ),
        ),
    ]
