# Generated by Django 4.2.6 on 2023-12-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_remove_baseuser_work_schedule_baseuser_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("waiter", "Waiter"),
                    ("barista", "Barista"),
                    ("admin", "Admin"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
