# Generated by Django 4.2.6 on 2023-11-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_baseuser_is_verify"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="is_verify",
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
