# Generated by Django 4.2.6 on 2023-12-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0011_alter_baseuser_options_alter_baseuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
