# Generated by Django 4.2.6 on 2023-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0013_rename_full_name_baseuser_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseuser",
            name="date",
        ),
        migrations.AddField(
            model_name="baseuser",
            name="friday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="friday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="monday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="monday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="saturday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="saturday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="sunday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="sunday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="thursday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="thursday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="tuesday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="tuesday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="wednesday_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="wednesday_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="friday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="monday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="saturday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="sunday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="thursday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="tuesday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="wednesday",
            field=models.BooleanField(default=False),
        ),
    ]
