# Generated by Django 4.2.6 on 2024-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', 'Свободно'), ('occupied', 'Занято')], default='free', max_length=20),
        ),
    ]
