# Generated by Django 4.2.6 on 2023-11-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraitem",
            name="choice_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_products",
                to="menu.category",
            ),
        ),
    ]
