# Generated by Django 4.2.6 on 2023-12-13 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="popular",
        ),
    ]
