# Generated by Django 4.2.6 on 2023-12-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0003_initial"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="menus", to="administrator.menuingredient"
            ),
        ),
    ]
