# Generated by Django 4.2.6 on 2023-12-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='ingredients',
        ),
    ]
