# Generated by Django 4.2.6 on 2023-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_extraitem_choice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='extra_items',
            field=models.ManyToManyField(blank=True, to='menu.extraitem', verbose_name='Дополнительные продукты'),
        ),
    ]
