# Generated by Django 4.2.6 on 2023-11-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_extraproduct_alter_extraitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraProduct',
        ),
    ]
