# Generated by Django 4.2.6 on 2023-11-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_extraitem_alter_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='media/category_images', verbose_name='Фото категории'),
        ),
    ]
