# Generated by Django 4.2.6 on 2023-11-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_extra_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='extra_items',
        ),
        migrations.AddField(
            model_name='menu',
            name='extra_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.extraitem', verbose_name='Дополнительные продукты'),
        ),
    ]
