# Generated by Django 4.2.6 on 2023-12-14 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_remove_menu_popular"),
        ("menu", "0003_remove_menu_ingredients"),
    ]

    operations = []
