# Generated by Django 4.2.6 on 2023-12-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_merge_20231214_2231"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="extra_product",
            field=models.ManyToManyField(to="menu.extraitem"),
        ),
    ]
