# Generated by Django 4.2.6 on 2023-11-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_extraitem_options_extraitem_choice_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category_images', verbose_name='Фото категории'),
        ),
    ]
