# Generated by Django 4.2.6 on 2023-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0006_extraitem_type_extra_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extraitem",
            name="type_extra_product",
            field=models.CharField(
                choices=[["Milk", "Молоко"], ["Syrop", "Сиропы"]],
                max_length=20,
                null=True,
                verbose_name="Доп. Продукт",
            ),
        ),
    ]
