# Generated by Django 4.2.6 on 2023-11-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_extra_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='extra_items',
        ),
    ]
