# Generated by Django 4.2.6 on 2023-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0008_menu_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="extra_product",
            field=models.ManyToManyField(blank=True, null=True, to="menu.extraitem"),
        ),
    ]
