# Generated by Django 4.2.6 on 2023-12-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0007_remove_branches_work_schedule_alter_branches_name"),
        ("menu", "0010_category_branch_alter_menu_extra_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="branch",
        ),
        migrations.AddField(
            model_name="category",
            name="branch",
            field=models.ManyToManyField(null=True, to="branches.branches"),
        ),
        migrations.AddField(
            model_name="menu",
            name="branch",
            field=models.ManyToManyField(null=True, to="branches.branches"),
        ),
    ]
