# Generated by Django 4.2.6 on 2023-12-20 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0007_remove_branches_work_schedule_alter_branches_name"),
        ("menu", "0012_remove_category_branch_remove_menu_branch_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("branch", "slug")},
        ),
    ]
