# Generated by Django 4.2.6 on 2023-12-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0013_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
