# Generated by Django 4.2.6 on 2024-01-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_alter_branches_options'),
        ('menu', '0016_menu_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='branches.branches', verbose_name='Филиал'),
        ),
    ]
