# Generated by Django 4.2.6 on 2023-12-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("customers", "0001_initial"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Новый", "Новый"),
                            ("В процессе", "В процессе"),
                            ("Готово", "Готово"),
                            ("Отменено", "Отменено"),
                            ("Завершено", "Завершено"),
                        ],
                        default="Новый",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_quantity", models.PositiveIntegerField(default=1)),
                ("extra_product_quantity", models.PositiveIntegerField(default=1)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches_in_order",
                        to="branches.branches",
                    ),
                ),
                (
                    "extra_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_order",
                        to="menu.extraitem",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="menu.menu",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="extra_products",
            field=models.ManyToManyField(
                through="order.OrderItem", to="menu.extraitem"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products_menu",
            field=models.ManyToManyField(through="order.OrderItem", to="menu.menu"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customeruser",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created"], name="order_order_created_708daa_idx"
            ),
        ),
    ]
