# Generated by Django 4.2.6 on 2023-12-11 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="staff",
        ),
    ]
