# Generated by Django 4.2.6 on 2023-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_extra_items'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='extra_product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extra_product',
            field=models.ManyToManyField(related_name='extra_order', to='menu.extraitem'),
        ),
    ]
