# Generated by Django 4.2.6 on 2024-01-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0015_alter_category_unique_together_remove_menu_branch_and_more"),
        ("order", "0002_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="menu.menu",
            ),
        ),
    ]
