# Generated by Django 4.2.6 on 2023-11-21 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_image'),
        ('order', '0002_alter_orderitem_extra_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extra_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_order', to='menu.extraitem'),
        ),
    ]
