# Generated by Django 4.2.6 on 2023-12-14 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="uniq_order_number",
        ),
    ]
