# Generated by Django 4.2.6 on 2023-12-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_remove_order_uniq_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custom_order_id",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
    ]
