# Generated by Django 4.2.6 on 2023-11-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_extra_items_menu_extra_items'),
        ('order', '0003_remove_orderitem_extra_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extra_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_order', to='menu.extraitem'),
        ),
    ]
