# Generated by Django 4.2.6 on 2023-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_bonuses_writen_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
