# Generated by Django 4.2.6 on 2023-12-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0007_remove_branches_work_schedule_alter_branches_name"),
        ("order", "0004_order_custom_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="bonuses_writen_off",
        ),
        migrations.RemoveField(
            model_name="order",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="order",
            name="extra_products",
        ),
        migrations.RemoveField(
            model_name="order",
            name="menu",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="bonuses_used",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="branches.branches",
            ),
        ),
    ]
