# Generated by Django 4.2.6 on 2023-12-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0007_remove_branches_work_schedule_alter_branches_name"),
        ("order", "0005_remove_order_bonuses_writen_off_remove_order_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="branch",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="branches.branches",
            ),
        ),
    ]
