# Generated by Django 4.2.6 on 2023-12-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0003_alter_branches_date"),
        ("order", "0006_alter_order_total_cost_after_bonuses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_cost_after_bonuses",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="branch",
        ),
        migrations.AlterField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="branches.branches",
            ),
        ),
    ]
