# Generated by Django 4.2.6 on 2024-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0017_category_branch"),
        ("order", "0006_alter_order_user_remove_orderitem_extra_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="extra_product",
            field=models.ManyToManyField(
                blank=True, related_name="extra_order", to="menu.extraitem"
            ),
        ),
    ]
