# Generated by Django 4.2.6 on 2023-12-19 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_order_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="branch",
        ),
    ]
