# Generated by Django 4.2.6 on 2023-12-13 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_remove_order_total_cost_after_bonuses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
    ]
