# Generated by Django 4.2.6 on 2023-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_remove_order_is_processed_remove_order_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("takeaway", "На вынос"), ("inplace", "В заведении")],
                default="takeaway",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("in_process", "В процессе"),
                    ("done", "Готово"),
                    ("cancelled", "Отменено"),
                    ("completed", "Завершено"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
